[[pages]]

path = "classroom.py"
name = "Algebra"
icon = "ğŸ§‘â€ğŸ«"

[[pages]]
path = "pages/create_assigment.py"
name = "Create Assignment"
icon = "ğŸ“"

[[pages]]
path = "chat_analysis.py"
name = "Chat Analysis"
icon = "ğŸ“Š"

[[pages]]
path = "pages/view_student.py"
name = "Student Details"
icon = "ğŸ“"